title: My blog
author: Mark Saroufim
description: My personal blog

highlighter: null
permalink: /:title

url: "http://www.marksaroufim.com"
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
exclude:
  - vendor
