title: My blog
author: Mark Saroufim
description: My personal blog

highlighter: null
permalink:

url:
baseurl:

markdown: kramdown
mathjax: true

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
exclude:
  - vendor
